### ISSUE TITLE
npm run preview 이슈

### ISSUE THREAD

**Issue by gwemin** [pronist/tistory-skin-hELLO#212]
localhost 환경이 아닌 웹 IDE(gitpod.io) 를 이용하여 

패키지 설치 후 tidory.config.example.js 설정 까지 했는데 이상하네요....

npm run preview 를 하니까

Invalid Host header  라고 뜨네요

Q. preview 는 localhost 에서만 동작하게 되어있나요???

**Comment by pronist** [comment]
@gwemin 안녕하세요.

웹 IDE 는 테스트 대상이 아니었어서 말씀드리기 어렵습니다. 로컬호스트 환경에서 `VSCode` 및 `WebStorm` 으로 테스트를 진행했습니다. 프리뷰는 티스토리 서버를 거쳐서 들어가기 때문에 티스토리에서 받아주지 않으면 처리될 수 없습니다. 프리뷰 서버는 `tidory.config.js` 에 `url`, `ts_session` 이 설정되어야 있어야 한다는 것도 참고해주시기 바랍니다.
